# C1 Check slash on end
#baseurl = "http://104.131.26.157/"
baseurl = "http://127.0.0.1/"

title = "Secret Chipmunk Postings"
theme = "hyde-x"
paginate = 10
DisqusShortname = "secretchipmunk"

[author]
    name = "Ron Parker"

[permalinks]
    # Optional. Change the permalink format for the 'post' content type.
    # The format shown here is the same one Jekyll/Octopress uses by default.
    # post = "/blog/:year/:month/:day/:title/"

[indexes]
    # Optional. Use if you want tags and lists.
    category = "categories"
    series = "series"

#
# All parameters below here are optional and can be mixed and matched.
#
[params]
    # Used when a given page doesn't set its own.
    defaultDescription = "Secret Chipmunk Post"
    defaultKeywords = "architecture,security,simplicity,infosec,entarch"

    # Changes sidebar background and link/accent colours.
    # See below for more colour options.
    # This also works: "theme-base-08 layout-reverse", or just "layout-reverse".
    theme = "theme-base-0b"

    # Select a syntax highight.
    # Check the static/css/highlight directory for options.
    highlight = "sunburst"

    # Displays under the author name in the sidebar, keep it short.
    tagline = "Architecture Security Simplicity"

    # Metadata used to drive integrations.
    googleAuthorship = "Your Google+ profile ID"
    googleAnalytics = "Your Google Analytics tracking code"
    gravatarHash = "fa3c588601b5b46b031bf8747b8e63df"

    # Sidebar social links, avoid enabling too many of these if possible.
    # These should be full URLs.
    github = ""
    linkedin = ""
    googleplus = ""
    facebook = ""
    twitter = "https://twitter.com/scmunk"



[[menu.main]]
    name = "Topics"
    identifier = "topic"
    url = "/topic/"
    weight = 100

[[menu.main]]
    name = "Resume"
    identifier = "resume"
    url = "/resume/"
    weight = 190

[[menu.main]]
    name = "About"
    identifier = "about"
    url = "/about/"
    weight = 200
